"""auth tokens email verification token version

Revision ID: 01d8a4238d07
Revises: a4d977e35603
Create Date: 2026-09-21 20:43:43.570322

Email verification, password reset, email change and session revocation
(docs/email-sendgrid.md):

- core.auth_tokens — single-use mailed tokens (sha256 only), per purpose.
- core.users.email_verified_at — NULL = not verified yet.
- core.users.token_version — the `tv` claim every JWT must match; server
  default 0, so tokens issued before this revision (no `tv` = 0) stay valid.

Generated with `alembic revision --autogenerate`; the schema operations below
are the generator's own output. As in a4d977e35603 it ALSO proposed recreating
`video_projects` / `effect_styles` in `public`, dropping them from
`tenant_default` and dropping `public.alembic_version` (the long-standing
schema-less tenant-model drift) — every one of those was removed.

The ONLY hand-written statement is the data backfill marked below.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '01d8a4238d07'
down_revision: str | Sequence[str] | None = 'a4d977e35603'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_tokens',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('new_email', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("purpose IN ('verify_email', 'reset_password', 'change_email')", name=op.f('ck_auth_tokens_purpose')),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], name=op.f('fk_auth_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_auth_tokens_token_hash')),
    schema='core'
    )
    op.create_index(op.f('ix_core_auth_tokens_user_id'), 'auth_tokens', ['user_id'], unique=False, schema='core')
    op.add_column('users', sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True), schema='core')
    op.add_column('users', sa.Column('token_version', sa.Integer(), server_default=sa.text('0'), nullable=False), schema='core')
    # ### end Alembic commands ###

    # ── HAND-WRITTEN (the only part of this file that is): data backfill ──
    # Grandfather every account that exists before verification ships: they
    # signed up when no verification existed, and the AI gate
    # (REQUIRE_VERIFIED_EMAIL_FOR_AI) must not lock them out on deploy.
    # A data change no autogenerate can express. The downgrade needs no
    # counterpart — dropping the column removes it.
    op.execute(
        "UPDATE core.users SET email_verified_at = created_at WHERE email_verified_at IS NULL"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version', schema='core')
    op.drop_column('users', 'email_verified_at', schema='core')
    op.drop_index(op.f('ix_core_auth_tokens_user_id'), table_name='auth_tokens', schema='core')
    op.drop_table('auth_tokens', schema='core')
    # ### end Alembic commands ###
