"""app_settings

Revision ID: 506967234d27
Revises: f201b6845092
Create Date: 2026-06-16 03:15:15.013521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '506967234d27'
down_revision: Union[str, Sequence[str], None] = 'f201b6845092'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scrape_interval', sa.BigInteger(), nullable=True),
    sa.Column('market_scrape_interval', sa.BigInteger(), nullable=True),
    sa.Column('llm_model', sa.String(length=128), nullable=True),
    sa.Column('llm_base_url', sa.String(length=256), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_settings'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    # ### end Alembic commands ###
