"""add model to stt_usage_logs

Seconds alone cannot be priced: scribe_v2_5 costs ~12.5x scribe_v2 per second
(measured against the live account — see packages/video/stt_pricing.py). The
model has to travel with each row or a cost figure is wrong by an order of
magnitude the day the setting changes.

Existing rows get '' and are priced at the higher rate, so an unknown row is
never mistaken for a cheap one.

Revision ID: 5acb26fefac3
Revises: 729422f4d43c
Create Date: 2026-08-12 05:00:00.000000

Autogenerated, then trimmed — the same unrelated drift as revision
729422f4d43c (see its docstring) was proposed again and removed.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '5acb26fefac3'
down_revision: Union[str, Sequence[str], None] = '729422f4d43c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'stt_usage_logs',
        sa.Column('model', sa.String(length=64), nullable=False, server_default=''),
        schema='core',
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('stt_usage_logs', 'model', schema='core')
