"""usage_accounts: the monthly window resets on the billing anniversary

Adds ``core.usage_accounts.monthly_anchor_day`` — the day of the month a
user's monthly allowance refills on, at 00:00 UTC. Until now the window was a
rolling 30 days from first use, so a customer billed on the 15th whose first
cut landed on the 12th got a fresh allowance on the 12th, three days before
paying for it, and drifting further every month. See packages/billing/runs.py.

AUTOGENERATED, then stripped. ``alembic revision --autogenerate`` against this
repo also proposed creating ``video_projects`` / ``effect_styles`` at the
default search_path and dropping the ``tenant_default`` copies and
``alembic_version``. That is an artifact of autogenerating with one tenant
schema on the search_path, not real drift; only the ``monthly_anchor_day``
column below is kept. The two backfill statements and the re-anchor loop were
added by hand — autogenerate writes schema, not data.

BACKFILL — what happens to a user who is mid-window when this deploys:

1. The anchor comes from ``billing_accounts.current_period_end``, the renewal
   date the Stripe sync already stored. A day clamped by a short February
   (a 31st subscription reading 28) is corrected by the next sync, which reads
   the subscription's own ``billing_cycle_anchor``.
2. An account with no subscription — admin-granted, enterprise, a plan set by
   hand — is pinned to the day its current window started on, so its reset day
   does not move at all.
3. Every row whose rolling window is still running keeps ``monthly_used`` and
   has ``monthly_started_at`` moved to the start of the billing period it is
   in. Without this the first read after deploy would find the window outside
   its period, roll it, and hand out a second month free. Nobody's usage is
   wiped and nobody's limit changes; the cost is that this ONE cycle is
   stretched or shortened by the gap between the user's old first-use day and
   their billing day — under a month, once. We would rather hand a paying
   customer a slightly early refill than hold their quota for up to an extra
   month, so the cycle always ends at the next anniversary rather than being
   pushed past it.
4. A row whose rolling window had already lapsed (nothing charged for 30 days)
   is left alone: it reads as unused either way and re-aligns at its next
   charge.

Revision ID: 60aadc49ba17
Revises: cbf873e519d6
Create Date: 2026-09-29 23:26:06.863465

"""
import calendar
from collections.abc import Sequence
from datetime import UTC, datetime, timedelta

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '60aadc49ba17'
down_revision: str | Sequence[str] | None = 'cbf873e519d6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _period_start(now: datetime, anchor_day: int) -> datetime:
    """The most recent billing anniversary at or before ``now``, clamped to a
    short month the way Stripe does — the same arithmetic as
    ``packages/billing/runs.py:period_start``, inlined so this migration keeps
    meaning what it meant when it ran."""
    def at(year: int, month: int) -> datetime:
        year, month = year + (month - 1) // 12, (month - 1) % 12 + 1
        last = calendar.monthrange(year, month)[1]
        return datetime(year, month, min(max(anchor_day, 1), last), tzinfo=UTC)

    this = at(now.year, now.month)
    return this if this <= now else at(now.year, now.month - 1)


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'usage_accounts',
        sa.Column('monthly_anchor_day', sa.SmallInteger(), nullable=True),
        schema='core',
    )

    bind = op.get_bind()
    # 1. The renewal day of everyone who has a subscription.
    bind.execute(
        sa.text(
            "UPDATE core.usage_accounts ua "
            "SET monthly_anchor_day = EXTRACT(DAY FROM ba.current_period_end AT TIME ZONE 'UTC') "
            "FROM core.billing_accounts ba "
            "WHERE ba.user_id = ua.user_id AND ba.current_period_end IS NOT NULL"
        )
    )
    # 2. Everyone else keeps the day their current window already started on.
    bind.execute(
        sa.text(
            "UPDATE core.usage_accounts "
            "SET monthly_anchor_day = EXTRACT(DAY FROM monthly_started_at AT TIME ZONE 'UTC') "
            "WHERE monthly_anchor_day IS NULL AND monthly_started_at IS NOT NULL"
        )
    )
    # 3. Re-anchor the windows that are still running, keeping ``monthly_used``.
    now = datetime.now(UTC)
    rows = bind.execute(
        sa.text(
            "SELECT user_id, monthly_anchor_day FROM core.usage_accounts "
            "WHERE monthly_started_at IS NOT NULL AND monthly_anchor_day IS NOT NULL "
            "AND monthly_started_at > :floor"
        ),
        {"floor": now - timedelta(days=30)},
    ).all()
    for user_id, anchor_day in rows:
        bind.execute(
            sa.text(
                "UPDATE core.usage_accounts SET monthly_started_at = :at WHERE user_id = :u"
            ),
            {"at": _period_start(now, int(anchor_day)), "u": int(user_id)},
        )


def downgrade() -> None:
    """Downgrade schema.

    Dropping the column puts every monthly window back on the rolling 30-day
    rule. The re-anchored ``monthly_started_at`` values are NOT restored —
    they are legitimate starts under either rule, so a downgraded account
    simply measures its 30 days from its billing day instead.
    """
    op.drop_column('usage_accounts', 'monthly_anchor_day', schema='core')
