"""add stt_usage_logs for per-user speech-to-text accounting

Speech-to-text goes through a single shared ElevenLabs account, so its own
account totals are every user's usage combined. This table is where a run's
billed audio length is attributed to the user who triggered it.

Revision ID: 729422f4d43c
Revises: c4d5e6f7a8b9
Create Date: 2026-08-12 04:50:17.390272

Autogenerated, then trimmed: the diff also picked up long-standing drift
between the models and this database (chat_sessions/effect_styles/
video_projects FK re-qualification, custom_table_meta.uid TEXT→VARCHAR(36),
a stale video_projects.cut_mode column) and — because the core tables resolve
through search_path — proposed dropping `users`, `tenants`, `memberships`,
`jobs`, `llm_usage_logs` and even `alembic_version`. None of that belongs to
this change and running it would destroy the database, so only the
stt_usage_logs statements are kept.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '729422f4d43c'
down_revision: Union[str, Sequence[str], None] = 'c4d5e6f7a8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'stt_usage_logs',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('tenant_id', sa.BigInteger(), nullable=False),
        sa.Column('reference_id', sa.String(length=64), nullable=True),
        sa.Column('audio_sec', sa.Float(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['tenant_id'],
            ['core.tenants.id'],
            name=op.f('fk_stt_usage_logs_tenant_id_tenants'),
            ondelete='CASCADE',
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['core.users.id'],
            name=op.f('fk_stt_usage_logs_user_id_users'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_stt_usage_logs')),
        schema='core',
    )
    op.create_index(
        'ix_stt_usage_logs_created_at',
        'stt_usage_logs',
        ['created_at'],
        unique=False,
        schema='core',
    )
    op.create_index(
        'ix_stt_usage_logs_user_id',
        'stt_usage_logs',
        ['user_id'],
        unique=False,
        schema='core',
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index('ix_stt_usage_logs_user_id', table_name='stt_usage_logs', schema='core')
    op.drop_index('ix_stt_usage_logs_created_at', table_name='stt_usage_logs', schema='core')
    op.drop_table('stt_usage_logs', schema='core')
