"""Token billing CORE-B: usage accounts, wallet, sign-up hashes.

docs/token-billing-design.md §3.4, §3.5, §3.8:

- usage_accounts: one row per user (created lazily) holding the rolling
  5-hour / weekly / monthly window state, open reservations, the wallet
  balance cache and scheduled plan changes / payment-failed grace. It is the
  row every reservation, settle and wallet debit locks (SELECT … FOR UPDATE).
- wallet_lots / wallet_ledger: the top-up balance (baht, 12-month lots) and
  its signed movement history. stripe_session_id is unique so a redelivered
  Checkout webhook credits once.
- users.signup_ip_hash / signup_device_hash: salted hashes for the free-tier
  abuse limits (never the raw IP or device id).

users.usage_reset_at is kept: the admin app still reads it; nothing enforces
from it any more (drop it once the admin UI migrates).

Generated with `alembic revision --autogenerate`; unrelated drift it picked up
(the shared tenant tables live outside the core metadata, and the
alembic_version table) was removed by hand. No data backfill.

Revision ID: 798eb04b7fef
Revises: c4b56f3a5120
Create Date: 2026-09-22 18:56:59.269420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '798eb04b7fef'
down_revision: Union[str, Sequence[str], None] = 'c4b56f3a5120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_accounts',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('five_hour_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('five_hour_used', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('weekly_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('weekly_used', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('monthly_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('monthly_used', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('reserved_tokens', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('wallet_balance_satang', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('wallet_reserved_satang', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('pending_plan', sa.String(length=32), nullable=True),
    sa.Column('pending_plan_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grace_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], name=op.f('fk_usage_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_usage_accounts')),
    schema='core'
    )
    op.create_table('wallet_lots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('amount_satang', sa.BigInteger(), nullable=False),
    sa.Column('remaining_satang', sa.BigInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stripe_session_id', sa.String(length=255), nullable=True),
    sa.Column('payment_method', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], name=op.f('fk_wallet_lots_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallet_lots')),
    sa.UniqueConstraint('stripe_session_id', name=op.f('uq_wallet_lots_stripe_session_id')),
    schema='core'
    )
    op.create_index('ix_wallet_lots_user_id_expires_at', 'wallet_lots', ['user_id', 'expires_at'], unique=False, schema='core')
    op.create_table('wallet_ledger',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('lot_id', sa.BigInteger(), nullable=True),
    sa.Column('run_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('amount_satang', sa.BigInteger(), nullable=False),
    sa.Column('balance_after_satang', sa.BigInteger(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['core.users.id'], name=op.f('fk_wallet_ledger_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lot_id'], ['core.wallet_lots.id'], name=op.f('fk_wallet_ledger_lot_id_wallet_lots'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['core.ai_runs.id'], name=op.f('fk_wallet_ledger_run_id_ai_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], name=op.f('fk_wallet_ledger_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallet_ledger')),
    schema='core'
    )
    op.create_index('ix_wallet_ledger_user_id_created_at', 'wallet_ledger', ['user_id', 'created_at'], unique=False, schema='core')
    op.add_column('users', sa.Column('signup_ip_hash', sa.String(length=64), nullable=True), schema='core')
    op.add_column('users', sa.Column('signup_device_hash', sa.String(length=64), nullable=True), schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'signup_device_hash', schema='core')
    op.drop_column('users', 'signup_ip_hash', schema='core')
    op.drop_index('ix_wallet_ledger_user_id_created_at', table_name='wallet_ledger', schema='core')
    op.drop_table('wallet_ledger', schema='core')
    op.drop_index('ix_wallet_lots_user_id_expires_at', table_name='wallet_lots', schema='core')
    op.drop_table('wallet_lots', schema='core')
    op.drop_table('usage_accounts', schema='core')
    # ### end Alembic commands ###
