"""billing accounts stripe events user display name

Revision ID: a4d977e35603
Revises: 32f7cd8e7c1d
Create Date: 2026-09-21 19:49:15.895033

Self-service accounts + Stripe billing (docs/billing-stripe.md):

- core.billing_accounts — one Stripe customer per user, and the subscription
  state the webhook last synced into `users.plan`.
- core.stripe_events — webhook event ids, the idempotency ledger.
- core.users.display_name — nullable; set at registration or PATCH /auth/me.

Generated with `alembic revision --autogenerate`; the three operations below
are the generator's own output. It ALSO proposed recreating `video_projects` /
`effect_styles` in `public`, dropping them from `tenant_default`, and dropping
`public.alembic_version` — the long-standing autogenerate drift from the
schema-less tenant models (see 32f7cd8e7c1d and daa132a95835). Every one of
those operations was removed: executing them would have destroyed the product.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a4d977e35603'
down_revision: str | Sequence[str] | None = '32f7cd8e7c1d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripe_events',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=128), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stripe_events')),
    schema='core'
    )
    op.create_table('billing_accounts',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('price_lookup_key', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('pm_brand', sa.String(length=32), nullable=True),
    sa.Column('pm_last4', sa.String(length=4), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], name=op.f('fk_billing_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_billing_accounts')),
    sa.UniqueConstraint('stripe_customer_id', name=op.f('uq_billing_accounts_stripe_customer_id')),
    schema='core'
    )
    op.add_column('users', sa.Column('display_name', sa.String(length=80), nullable=True), schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'display_name', schema='core')
    op.drop_table('billing_accounts', schema='core')
    op.drop_table('stripe_events', schema='core')
    # ### end Alembic commands ###
