"""merge blog and weekly overage heads

Revision ID: bae823bb28cd
Revises: b4981f7d5cbb, cabaf0a983ae
Create Date: 2026-10-02 00:44:39.738347

Generated by `alembic merge`. The blog branch (cabaf0a983ae: blog tables and
MCP OAuth in core) and the weekly-overage column (b4981f7d5cbb: core.usage_accounts)
were written in parallel and touch disjoint tables, so the merge carries no DDL.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bae823bb28cd'
down_revision: Union[str, Sequence[str], None] = ('b4981f7d5cbb', 'cabaf0a983ae')
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    pass


def downgrade() -> None:
    """Downgrade schema."""
    pass
