"""Usage cost recording: per-request usage rows, ai_runs, FX, vendor invoices.

Token billing CORE-A (docs/token-billing-design.md §3.1–3.3, §3.6):

- llm_usage_logs / stt_usage_logs gain the run they belong to (run_id, job_id),
  the attempt status (ok / failed / retry), cached input tokens, the rate-card
  tokens charged + the rate-card version, and the real vendor cost in THB with
  the FX rate it was priced at. idem_key makes a replay from the Redis outbox
  insert once. STT rows become one per transcribed file (clip_index) and say
  whether keyterms were sent (they carry a per-hour surcharge).
- ai_runs: one row per paid run (core.jobs ids are reused per project).
  CORE-B fills in the reservation / settle behaviour.
- fx_rates: the daily fetched USD->THB rate; vendor_invoices: what each vendor
  actually billed per month, for reconciliation.

Every new NOT NULL column has a server default, so existing rows (and any raw
INSERT that predates this) stay valid; legacy rows keep tokens = 0 and
cost_thb NULL — no backfill here.

Generated with `alembic revision --autogenerate`; unrelated drift it picked up
(the shared tenant tables live outside the core metadata, and the
alembic_version table) was removed by hand.

Revision ID: c4b56f3a5120
Revises: cc9a45fa2da7
Create Date: 2026-09-22 18:30:53.679895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4b56f3a5120'
down_revision: Union[str, Sequence[str], None] = 'cc9a45fa2da7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('usd_thb', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fx_rates')),
    sa.UniqueConstraint('rate_date', 'source', name='uq_fx_rates_rate_date_source'),
    schema='core'
    )
    op.create_index(op.f('ix_core_fx_rates_rate_date'), 'fx_rates', ['rate_date'], unique=False, schema='core')
    op.create_table('ai_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tenant_id', sa.BigInteger(), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=True),
    sa.Column('reference_id', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=True),
    sa.Column('engine', sa.String(length=32), nullable=True),
    sa.Column('precision', sa.String(length=32), nullable=True),
    sa.Column('media_sec', sa.Float(), server_default='0', nullable=False),
    sa.Column('estimate_tokens', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('reserved_tokens', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('reserved_wallet_satang', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('ceiling_tokens', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('actual_tokens', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('charged_tokens', sa.BigInteger(), nullable=True),
    sa.Column('charged_wallet_satang', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='queued', nullable=False),
    sa.Column('outcome', sa.String(length=48), nullable=True),
    sa.Column('unlimited', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('estimator_version', sa.String(length=16), nullable=True),
    sa.Column('rate_version', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['core.tenants.id'], name=op.f('fk_ai_runs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], name=op.f('fk_ai_runs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_runs')),
    schema='core'
    )
    op.create_index('ix_ai_runs_created_at', 'ai_runs', ['created_at'], unique=False, schema='core')
    op.create_index('ix_ai_runs_user_id_status', 'ai_runs', ['user_id', 'status'], unique=False, schema='core')
    op.create_table('vendor_invoices',
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('vendor', sa.String(length=16), nullable=False),
    sa.Column('amount_thb', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['core.users.id'], name=op.f('fk_vendor_invoices_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('month', 'vendor', name=op.f('pk_vendor_invoices')),
    schema='core'
    )
    op.add_column('llm_usage_logs', sa.Column('cached_tokens', sa.Integer(), server_default='0', nullable=False), schema='core')
    op.add_column('llm_usage_logs', sa.Column('run_id', sa.String(length=32), nullable=True), schema='core')
    op.add_column('llm_usage_logs', sa.Column('job_id', sa.String(length=64), nullable=True), schema='core')
    op.add_column('llm_usage_logs', sa.Column('status', sa.String(length=16), server_default='ok', nullable=False), schema='core')
    op.add_column('llm_usage_logs', sa.Column('tokens', sa.BigInteger(), server_default='0', nullable=False), schema='core')
    op.add_column('llm_usage_logs', sa.Column('rate_version', sa.String(length=16), nullable=True), schema='core')
    op.add_column('llm_usage_logs', sa.Column('cost_thb', sa.Numeric(precision=12, scale=4), nullable=True), schema='core')
    op.add_column('llm_usage_logs', sa.Column('fx_rate', sa.Numeric(precision=10, scale=4), nullable=True), schema='core')
    op.add_column('llm_usage_logs', sa.Column('idem_key', sa.String(length=36), nullable=True), schema='core')
    op.create_index('ix_llm_usage_logs_run_id', 'llm_usage_logs', ['run_id'], unique=False, schema='core')
    op.create_index('ix_llm_usage_logs_user_id_created_at', 'llm_usage_logs', ['user_id', 'created_at'], unique=False, schema='core')
    op.create_unique_constraint(op.f('uq_llm_usage_logs_idem_key'), 'llm_usage_logs', ['idem_key'], schema='core')
    op.create_foreign_key(op.f('fk_llm_usage_logs_run_id_ai_runs'), 'llm_usage_logs', 'ai_runs', ['run_id'], ['id'], source_schema='core', referent_schema='core', ondelete='SET NULL')
    op.add_column('stt_usage_logs', sa.Column('keyterms', sa.Boolean(), server_default='false', nullable=False), schema='core')
    op.add_column('stt_usage_logs', sa.Column('clip_index', sa.Integer(), nullable=True), schema='core')
    op.add_column('stt_usage_logs', sa.Column('run_id', sa.String(length=32), nullable=True), schema='core')
    op.add_column('stt_usage_logs', sa.Column('job_id', sa.String(length=64), nullable=True), schema='core')
    op.add_column('stt_usage_logs', sa.Column('status', sa.String(length=16), server_default='ok', nullable=False), schema='core')
    op.add_column('stt_usage_logs', sa.Column('tokens', sa.BigInteger(), server_default='0', nullable=False), schema='core')
    op.add_column('stt_usage_logs', sa.Column('rate_version', sa.String(length=16), nullable=True), schema='core')
    op.add_column('stt_usage_logs', sa.Column('cost_thb', sa.Numeric(precision=12, scale=4), nullable=True), schema='core')
    op.add_column('stt_usage_logs', sa.Column('fx_rate', sa.Numeric(precision=10, scale=4), nullable=True), schema='core')
    op.add_column('stt_usage_logs', sa.Column('idem_key', sa.String(length=36), nullable=True), schema='core')
    op.create_index('ix_stt_usage_logs_run_id', 'stt_usage_logs', ['run_id'], unique=False, schema='core')
    op.create_unique_constraint(op.f('uq_stt_usage_logs_idem_key'), 'stt_usage_logs', ['idem_key'], schema='core')
    op.create_foreign_key(op.f('fk_stt_usage_logs_run_id_ai_runs'), 'stt_usage_logs', 'ai_runs', ['run_id'], ['id'], source_schema='core', referent_schema='core', ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_stt_usage_logs_run_id_ai_runs'), 'stt_usage_logs', schema='core', type_='foreignkey')
    op.drop_constraint(op.f('uq_stt_usage_logs_idem_key'), 'stt_usage_logs', schema='core', type_='unique')
    op.drop_index('ix_stt_usage_logs_run_id', table_name='stt_usage_logs', schema='core')
    op.drop_column('stt_usage_logs', 'idem_key', schema='core')
    op.drop_column('stt_usage_logs', 'fx_rate', schema='core')
    op.drop_column('stt_usage_logs', 'cost_thb', schema='core')
    op.drop_column('stt_usage_logs', 'rate_version', schema='core')
    op.drop_column('stt_usage_logs', 'tokens', schema='core')
    op.drop_column('stt_usage_logs', 'status', schema='core')
    op.drop_column('stt_usage_logs', 'job_id', schema='core')
    op.drop_column('stt_usage_logs', 'run_id', schema='core')
    op.drop_column('stt_usage_logs', 'clip_index', schema='core')
    op.drop_column('stt_usage_logs', 'keyterms', schema='core')
    op.drop_constraint(op.f('fk_llm_usage_logs_run_id_ai_runs'), 'llm_usage_logs', schema='core', type_='foreignkey')
    op.drop_constraint(op.f('uq_llm_usage_logs_idem_key'), 'llm_usage_logs', schema='core', type_='unique')
    op.drop_index('ix_llm_usage_logs_user_id_created_at', table_name='llm_usage_logs', schema='core')
    op.drop_index('ix_llm_usage_logs_run_id', table_name='llm_usage_logs', schema='core')
    op.drop_column('llm_usage_logs', 'idem_key', schema='core')
    op.drop_column('llm_usage_logs', 'fx_rate', schema='core')
    op.drop_column('llm_usage_logs', 'cost_thb', schema='core')
    op.drop_column('llm_usage_logs', 'rate_version', schema='core')
    op.drop_column('llm_usage_logs', 'tokens', schema='core')
    op.drop_column('llm_usage_logs', 'status', schema='core')
    op.drop_column('llm_usage_logs', 'job_id', schema='core')
    op.drop_column('llm_usage_logs', 'run_id', schema='core')
    op.drop_column('llm_usage_logs', 'cached_tokens', schema='core')
    op.drop_table('vendor_invoices', schema='core')
    op.drop_index('ix_ai_runs_user_id_status', table_name='ai_runs', schema='core')
    op.drop_index('ix_ai_runs_created_at', table_name='ai_runs', schema='core')
    op.drop_table('ai_runs', schema='core')
    op.drop_index(op.f('ix_core_fx_rates_rate_date'), table_name='fx_rates', schema='core')
    op.drop_table('fx_rates', schema='core')
    # ### end Alembic commands ###
