"""Blog: posts, categories, tags, images, audit log, and the blog MCP server's OAuth tables.

Generated with `alembic revision --autogenerate` against a scratch database at
df3fde09f064, then trimmed: autogenerate also reported long-standing drift
unrelated to this change (the per-tenant `video_projects` / `effect_styles`
tables living in `tenant_default`, and `public.alembic_version`), which it
would have DROPPED. Those operations were removed.

Hand-written on top (autogenerate cannot express data): the seed of the four
starting categories. Categories are a fixed set — the MCP server cannot create
one — so the blog needs them from the first deploy.

Revision ID: cabaf0a983ae
Revises: df3fde09f064
Create Date: 2026-10-01 18:14:27.882345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cabaf0a983ae'
down_revision: Union[str, Sequence[str], None] = 'df3fde09f064'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

#: The starting categories (hand-written seed; see the module docstring).
CATEGORIES = [
    {"slug": "editing-tips", "name": "เทคนิคตัดต่อ", "sort_order": 1,
     "description": "วิธีตัดคลิปสั้นให้เร็วและดูลื่น ตั้งแต่ถ่ายจนถึงเกลาไทม์ไลน์"},
    {"slug": "subtitles-audio", "name": "ซับไทยและเสียง", "sort_order": 2,
     "description": "ซับไทย การถอดเสียง เสียงพากย์ และเพลงประกอบในคลิปสั้น"},
    {"slug": "selling-on-tiktok", "name": "ขายของบน TikTok", "sort_order": 3,
     "description": "คลิปรีวิวและคลิปปักตะกร้าสำหรับครีเอเตอร์ TikTok Affiliate"},
    {"slug": "content-ideas", "name": "ไอเดียคอนเทนต์", "sort_order": 4,
     "description": "ไอเดียและโครงคลิปสั้นที่ถ่ายเองลงเองได้"},
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_audit_log')),
    schema='core'
    )
    op.create_index('ix_blog_audit_log_at', 'blog_audit_log', ['at'], unique=False, schema='core')
    op.create_table('blog_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=300), server_default='', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_categories')),
    sa.UniqueConstraint('slug', name=op.f('uq_blog_categories_slug')),
    schema='core'
    )
    op.create_table('blog_images',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('key', sa.String(length=300), nullable=False),
    sa.Column('mime', sa.String(length=40), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('alt', sa.String(length=300), nullable=False),
    sa.Column('uploaded_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_images')),
    sa.UniqueConstraint('key', name=op.f('uq_blog_images_key')),
    schema='core'
    )
    op.create_table('blog_oauth_clients',
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('info', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('secret_enc', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('client_id', name=op.f('pk_blog_oauth_clients')),
    schema='core'
    )
    op.create_table('blog_tags',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_tags')),
    sa.UniqueConstraint('slug', name=op.f('uq_blog_tags_slug')),
    schema='core'
    )
    op.create_table('blog_oauth_grants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('admin_user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('scopes', sa.String(length=200), nullable=False),
    sa.Column('resource', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['core.users.id'], name=op.f('fk_blog_oauth_grants_admin_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['core.blog_oauth_clients.client_id'], name=op.f('fk_blog_oauth_grants_client_id_blog_oauth_clients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_oauth_grants')),
    schema='core'
    )
    op.create_index(op.f('ix_core_blog_oauth_grants_admin_user_id'), 'blog_oauth_grants', ['admin_user_id'], unique=False, schema='core')
    op.create_index(op.f('ix_core_blog_oauth_grants_client_id'), 'blog_oauth_grants', ['client_id'], unique=False, schema='core')
    op.create_table('blog_posts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('meta_title', sa.String(length=60), nullable=False),
    sa.Column('meta_description', sa.String(length=160), nullable=False),
    sa.Column('excerpt', sa.String(length=300), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('cover_alt', sa.String(length=300), nullable=True),
    sa.Column('cover_width', sa.Integer(), nullable=True),
    sa.Column('cover_height', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('faq', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('author', sa.String(length=80), server_default='Noey Studio', nullable=False),
    sa.Column('source', sa.String(length=8), server_default='ai', nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('ai', 'human')", name=op.f('ck_blog_posts_source')),
    sa.CheckConstraint("status IN ('draft', 'published', 'unpublished')", name=op.f('ck_blog_posts_status')),
    sa.ForeignKeyConstraint(['category_id'], ['core.blog_categories.id'], name=op.f('fk_blog_posts_category_id_blog_categories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_posts')),
    sa.UniqueConstraint('slug', name=op.f('uq_blog_posts_slug')),
    schema='core'
    )
    op.create_index('ix_blog_posts_status_published_at', 'blog_posts', ['status', 'published_at'], unique=False, schema='core')
    op.create_index(op.f('ix_core_blog_posts_category_id'), 'blog_posts', ['category_id'], unique=False, schema='core')
    op.create_table('blog_oauth_requests',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('admin_user_id', sa.BigInteger(), nullable=True),
    sa.Column('code_hash', sa.String(length=64), nullable=True),
    sa.Column('code_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('code_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('grant_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['core.users.id'], name=op.f('fk_blog_oauth_requests_admin_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['core.blog_oauth_clients.client_id'], name=op.f('fk_blog_oauth_requests_client_id_blog_oauth_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grant_id'], ['core.blog_oauth_grants.id'], name=op.f('fk_blog_oauth_requests_grant_id_blog_oauth_grants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_oauth_requests')),
    sa.UniqueConstraint('code_hash', name=op.f('uq_blog_oauth_requests_code_hash')),
    schema='core'
    )
    op.create_index(op.f('ix_core_blog_oauth_requests_client_id'), 'blog_oauth_requests', ['client_id'], unique=False, schema='core')
    op.create_table('blog_post_tags',
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['core.blog_posts.id'], name=op.f('fk_blog_post_tags_post_id_blog_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['core.blog_tags.id'], name=op.f('fk_blog_post_tags_tag_id_blog_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'tag_id', name=op.f('pk_blog_post_tags')),
    schema='core'
    )
    op.create_index(op.f('ix_core_blog_post_tags_tag_id'), 'blog_post_tags', ['tag_id'], unique=False, schema='core')

    categories = sa.table(
        "blog_categories",
        sa.column("slug", sa.String),
        sa.column("name", sa.String),
        sa.column("description", sa.String),
        sa.column("sort_order", sa.Integer),
        schema="core",
    )
    op.bulk_insert(categories, CATEGORIES)


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_core_blog_post_tags_tag_id'), table_name='blog_post_tags', schema='core')
    op.drop_table('blog_post_tags', schema='core')
    op.drop_index(op.f('ix_core_blog_oauth_requests_client_id'), table_name='blog_oauth_requests', schema='core')
    op.drop_table('blog_oauth_requests', schema='core')
    op.drop_index(op.f('ix_core_blog_posts_category_id'), table_name='blog_posts', schema='core')
    op.drop_index('ix_blog_posts_status_published_at', table_name='blog_posts', schema='core')
    op.drop_table('blog_posts', schema='core')
    op.drop_index(op.f('ix_core_blog_oauth_grants_client_id'), table_name='blog_oauth_grants', schema='core')
    op.drop_index(op.f('ix_core_blog_oauth_grants_admin_user_id'), table_name='blog_oauth_grants', schema='core')
    op.drop_table('blog_oauth_grants', schema='core')
    op.drop_table('blog_tags', schema='core')
    op.drop_table('blog_oauth_clients', schema='core')
    op.drop_table('blog_images', schema='core')
    op.drop_table('blog_categories', schema='core')
    op.drop_index('ix_blog_audit_log_at', table_name='blog_audit_log', schema='core')
    op.drop_table('blog_audit_log', schema='core')
