"""admin dashboard tables

Core-schema tables for the admin app: OTP login challenges, remembered
devices, server-side admin sessions, the append-only audit log, owner-edited
settings (cost config) and admin-set plan prices. Autogenerated; the
tenant_default drift autogenerate also reports (the tenant tables are mapped
without a schema) was removed by hand — it is unrelated to this change.

Revision ID: cc9a45fa2da7
Revises: 01d8a4238d07
Create Date: 2026-09-22 14:00:38.864327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc9a45fa2da7'
down_revision: Union[str, Sequence[str], None] = '01d8a4238d07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('target_user_id', sa.BigInteger(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['core.users.id'], name=op.f('fk_admin_audit_events_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['core.users.id'], name=op.f('fk_admin_audit_events_target_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_audit_events')),
    schema='core'
    )
    op.create_index('ix_admin_audit_events_action_email', 'admin_audit_events', ['action', 'email'], unique=False, schema='core')
    op.create_index('ix_admin_audit_events_created_at', 'admin_audit_events', ['created_at'], unique=False, schema='core')
    op.create_table('admin_devices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], name=op.f('fk_admin_devices_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_devices')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_admin_devices_token_hash')),
    schema='core'
    )
    op.create_index(op.f('ix_core_admin_devices_user_id'), 'admin_devices', ['user_id'], unique=False, schema='core')
    op.create_table('admin_login_challenges',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('resends', sa.Integer(), server_default='0', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], name=op.f('fk_admin_login_challenges_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_login_challenges')),
    schema='core'
    )
    op.create_index(op.f('ix_core_admin_login_challenges_user_id'), 'admin_login_challenges', ['user_id'], unique=False, schema='core')
    op.create_table('admin_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['core.users.id'], name=op.f('fk_admin_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_sessions')),
    schema='core'
    )
    op.create_index(op.f('ix_core_admin_sessions_user_id'), 'admin_sessions', ['user_id'], unique=False, schema='core')
    op.create_table('admin_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['core.users.id'], name=op.f('fk_admin_settings_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_admin_settings')),
    schema='core'
    )
    op.create_table('plan_price_overrides',
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('unit_amount', sa.BigInteger(), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['core.users.id'], name=op.f('fk_plan_price_overrides_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('tier', name=op.f('pk_plan_price_overrides')),
    schema='core'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('plan_price_overrides', schema='core')
    op.drop_table('admin_settings', schema='core')
    op.drop_index(op.f('ix_core_admin_sessions_user_id'), table_name='admin_sessions', schema='core')
    op.drop_table('admin_sessions', schema='core')
    op.drop_index(op.f('ix_core_admin_login_challenges_user_id'), table_name='admin_login_challenges', schema='core')
    op.drop_table('admin_login_challenges', schema='core')
    op.drop_index(op.f('ix_core_admin_devices_user_id'), table_name='admin_devices', schema='core')
    op.drop_table('admin_devices', schema='core')
    op.drop_index('ix_admin_audit_events_created_at', table_name='admin_audit_events', schema='core')
    op.drop_index('ix_admin_audit_events_action_email', table_name='admin_audit_events', schema='core')
    op.drop_table('admin_audit_events', schema='core')
    # ### end Alembic commands ###
