"""wallet lot payment intent

Revision ID: ce0c8c1ea951
Revises: 798eb04b7fef
Create Date: 2026-09-22 19:59:59.947736

Autogenerated. ``wallet_lots.stripe_payment_intent`` lets a Stripe refund or
dispute of a top-up (``charge.refunded`` / ``charge.dispute.created``, which
name the PaymentIntent, not the Checkout Session) find the lot to take back —
packages/billing/topup.py:reverse_from_event.

Removed from the generated file: the usual tenant-table drift (autogenerate
sees the per-tenant ``video_projects`` / ``effect_styles`` in
``tenant_default`` as "removed" and the bare ones as "added", plus a
spurious ``alembic_version`` drop) — tenant schemas are managed by
packages/db/tenancy.py, not by this migration chain. No backfill: lots
credited before this revision are resolved through Stripe once and the id is
stored then.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ce0c8c1ea951'
down_revision: Union[str, Sequence[str], None] = '798eb04b7fef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('wallet_lots', sa.Column('stripe_payment_intent', sa.String(length=255), nullable=True), schema='core')
    op.create_index(op.f('ix_core_wallet_lots_stripe_payment_intent'), 'wallet_lots', ['stripe_payment_intent'], unique=False, schema='core')


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_core_wallet_lots_stripe_payment_intent'), table_name='wallet_lots', schema='core')
    op.drop_column('wallet_lots', 'stripe_payment_intent', schema='core')
