"""blog: media assets of every kind, HTML visuals, the writing brief and the content plan.

Generated with `alembic revision --autogenerate` against a scratch database at
bae823bb28cd, then trimmed: autogenerate also proposed creating/dropping the
per-tenant `effect_styles` / `video_projects` tables and `alembic_version`
(the usual tenant-schema drift — those live in `tenant_<slug>` schemas, which
the core metadata does not describe). That part was removed.

- `core.blog_images` keeps its name but now holds every stored blog media
  asset: `kind` (image | video | file), `origin` (upload | render_cover |
  library | brand), the owner's library fields (category, description, tags,
  archived_at) and a video's poster + duration. Every existing row is an image
  uploaded through `upload_image` — exactly what the server defaults say.
- `core.blog_visuals`: in-article HTML visuals (create_visual). Stored as files
  under the bucket's `visual/` prefix, served from the embed origin; the row
  holds the canvas size, alt/caption, `animated` and the creating connection.
- `core.blog_brief`: one row (id = 1) the admin edits; created on first save.
- `core.blog_content_plan`: the owner's ordered topics; `mark_topic_done`
  links a topic to the post that covers it (by slug, not a foreign key).

Revision ID: ddc30bda9b1f
Revises: bae823bb28cd
Create Date: 2026-10-02 03:24:19.356399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ddc30bda9b1f'
down_revision: Union[str, Sequence[str], None] = 'bae823bb28cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_content_plan',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('status', sa.String(length=16), server_default='planned', nullable=False),
    sa.Column('post_slug', sa.String(length=80), nullable=True),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('planned', 'writing', 'done', 'skipped')", name=op.f('ck_blog_content_plan_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_content_plan')),
    schema='core'
    )
    op.create_index('ix_blog_content_plan_status_position', 'blog_content_plan', ['status', 'position'], unique=False, schema='core')
    op.create_table('blog_visuals',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=300), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('alt', sa.String(length=300), nullable=False),
    sa.Column('caption', sa.String(length=300), nullable=True),
    sa.Column('animated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_visuals')),
    sa.UniqueConstraint('key', name=op.f('uq_blog_visuals_key')),
    schema='core'
    )
    op.create_index(op.f('ix_core_blog_visuals_created_by'), 'blog_visuals', ['created_by'], unique=False, schema='core')
    op.create_table('blog_brief',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tone', sa.String(length=1000), server_default='', nullable=False),
    sa.Column('focus_topics', sa.String(length=2000), server_default='', nullable=False),
    sa.Column('avoid_topics', sa.String(length=2000), server_default='', nullable=False),
    sa.Column('length', sa.String(length=500), server_default='', nullable=False),
    sa.Column('media', sa.String(length=500), server_default='', nullable=False),
    sa.Column('monthly_note', sa.String(length=2000), server_default='', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.CheckConstraint('id = 1', name=op.f('ck_blog_brief_single_row')),
    sa.ForeignKeyConstraint(['updated_by'], ['core.users.id'], name=op.f('fk_blog_brief_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_brief')),
    schema='core'
    )
    op.add_column('blog_images', sa.Column('kind', sa.String(length=16), server_default='image', nullable=False), schema='core')
    op.add_column('blog_images', sa.Column('origin', sa.String(length=24), server_default='upload', nullable=False), schema='core')
    op.add_column('blog_images', sa.Column('category', sa.String(length=16), nullable=True), schema='core')
    op.add_column('blog_images', sa.Column('description', sa.String(length=1000), server_default='', nullable=False), schema='core')
    op.add_column('blog_images', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False), schema='core')
    op.add_column('blog_images', sa.Column('poster_url', sa.String(length=500), nullable=True), schema='core')
    op.add_column('blog_images', sa.Column('poster_key', sa.String(length=300), nullable=True), schema='core')
    op.add_column('blog_images', sa.Column('duration_ms', sa.Integer(), nullable=True), schema='core')
    op.add_column('blog_images', sa.Column('filename', sa.String(length=200), nullable=True), schema='core')
    op.add_column('blog_images', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True), schema='core')
    op.create_index('ix_blog_images_origin_category', 'blog_images', ['origin', 'category'], unique=False, schema='core')
    # ### end Alembic commands ###
    # Not emitted by autogenerate (it does not compare CHECK constraints of an
    # existing table); these mirror BlogImage.__table_args__ so the database
    # itself refuses an unknown kind / origin / category.
    op.create_check_constraint(op.f('ck_blog_images_kind'), 'blog_images', "kind IN ('image', 'video', 'file')", schema='core')
    op.create_check_constraint(
        op.f('ck_blog_images_origin'), 'blog_images', "origin IN ('upload', 'render_cover', 'library', 'brand')", schema='core'
    )
    op.create_check_constraint(
        op.f('ck_blog_images_category'), 'blog_images',
        "category IS NULL OR category IN ('screenshot', 'demo', 'logo', 'file')", schema='core',
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(op.f('ck_blog_images_category'), 'blog_images', schema='core', type_='check')
    op.drop_constraint(op.f('ck_blog_images_origin'), 'blog_images', schema='core', type_='check')
    op.drop_constraint(op.f('ck_blog_images_kind'), 'blog_images', schema='core', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_blog_images_origin_category', table_name='blog_images', schema='core')
    op.drop_column('blog_images', 'archived_at', schema='core')
    op.drop_column('blog_images', 'filename', schema='core')
    op.drop_column('blog_images', 'duration_ms', schema='core')
    op.drop_column('blog_images', 'poster_key', schema='core')
    op.drop_column('blog_images', 'poster_url', schema='core')
    op.drop_column('blog_images', 'tags', schema='core')
    op.drop_column('blog_images', 'description', schema='core')
    op.drop_column('blog_images', 'category', schema='core')
    op.drop_column('blog_images', 'origin', schema='core')
    op.drop_column('blog_images', 'kind', schema='core')
    op.drop_table('blog_brief', schema='core')
    op.drop_index(op.f('ix_core_blog_visuals_created_by'), table_name='blog_visuals', schema='core')
    op.drop_table('blog_visuals', schema='core')
    op.drop_index('ix_blog_content_plan_status_position', table_name='blog_content_plan', schema='core')
    op.drop_table('blog_content_plan', schema='core')
    # ### end Alembic commands ###
