"""tiktok_csv_tables

Revision ID: efc010eddd8c
Revises: 506967234d27
Create Date: 2026-06-19 04:21:29.476431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efc010eddd8c'
down_revision: Union[str, Sequence[str], None] = '506967234d27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csv_import_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('export_date', sa.Date(), nullable=False),
    sa.Column('filenames', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rows_imported', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_csv_import_runs'))
    )
    op.create_index(op.f('ix_csv_import_runs_created_at'), 'csv_import_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_csv_import_runs_export_date'), 'csv_import_runs', ['export_date'], unique=False)
    op.create_table('follower_activity',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('export_date', sa.Date(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('active_followers', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_follower_activity')),
    sa.UniqueConstraint('export_date', 'date', 'hour', name='uq_follower_activity_export_date_date_hour')
    )
    op.create_index(op.f('ix_follower_activity_date'), 'follower_activity', ['date'], unique=False)
    op.create_index(op.f('ix_follower_activity_export_date'), 'follower_activity', ['export_date'], unique=False)
    op.create_table('follower_gender',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('export_date', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=16), nullable=False),
    sa.Column('distribution', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_follower_gender')),
    sa.UniqueConstraint('export_date', 'gender', name='uq_follower_gender_export_date_gender')
    )
    op.create_index(op.f('ix_follower_gender_export_date'), 'follower_gender', ['export_date'], unique=False)
    op.create_table('follower_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('export_date', sa.Date(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=False),
    sa.Column('net_change', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_follower_history')),
    sa.UniqueConstraint('export_date', 'date', name='uq_follower_history_export_date_date')
    )
    op.create_index(op.f('ix_follower_history_date'), 'follower_history', ['date'], unique=False)
    op.create_index(op.f('ix_follower_history_export_date'), 'follower_history', ['export_date'], unique=False)
    op.create_table('follower_territory',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('export_date', sa.Date(), nullable=False),
    sa.Column('territory', sa.String(length=16), nullable=False),
    sa.Column('distribution', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_follower_territory')),
    sa.UniqueConstraint('export_date', 'territory', name='uq_follower_territory_export_date_territory')
    )
    op.create_index(op.f('ix_follower_territory_export_date'), 'follower_territory', ['export_date'], unique=False)
    op.create_table('overview_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('export_date', sa.Date(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('video_views', sa.Integer(), nullable=False),
    sa.Column('profile_views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_overview_daily')),
    sa.UniqueConstraint('export_date', 'date', name='uq_overview_daily_export_date_date')
    )
    op.create_index(op.f('ix_overview_daily_date'), 'overview_daily', ['date'], unique=False)
    op.create_index(op.f('ix_overview_daily_export_date'), 'overview_daily', ['export_date'], unique=False)
    op.create_table('video_content',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('export_date', sa.Date(), nullable=False),
    sa.Column('video_id', sa.String(length=64), nullable=False),
    sa.Column('video_url', sa.String(length=512), nullable=False),
    sa.Column('video_title', sa.Text(), nullable=False),
    sa.Column('post_date', sa.Date(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_video_content')),
    sa.UniqueConstraint('export_date', 'video_id', name='uq_video_content_export_date_video_id')
    )
    op.create_index(op.f('ix_video_content_export_date'), 'video_content', ['export_date'], unique=False)
    op.create_index(op.f('ix_video_content_video_id'), 'video_content', ['video_id'], unique=False)
    op.create_table('viewers_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('export_date', sa.Date(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_viewers', sa.Integer(), nullable=True),
    sa.Column('new_viewers', sa.Integer(), nullable=True),
    sa.Column('returning_viewers', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_viewers_daily')),
    sa.UniqueConstraint('export_date', 'date', name='uq_viewers_daily_export_date_date')
    )
    op.create_index(op.f('ix_viewers_daily_date'), 'viewers_daily', ['date'], unique=False)
    op.create_index(op.f('ix_viewers_daily_export_date'), 'viewers_daily', ['export_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_viewers_daily_export_date'), table_name='viewers_daily')
    op.drop_index(op.f('ix_viewers_daily_date'), table_name='viewers_daily')
    op.drop_table('viewers_daily')
    op.drop_index(op.f('ix_video_content_video_id'), table_name='video_content')
    op.drop_index(op.f('ix_video_content_export_date'), table_name='video_content')
    op.drop_table('video_content')
    op.drop_index(op.f('ix_overview_daily_export_date'), table_name='overview_daily')
    op.drop_index(op.f('ix_overview_daily_date'), table_name='overview_daily')
    op.drop_table('overview_daily')
    op.drop_index(op.f('ix_follower_territory_export_date'), table_name='follower_territory')
    op.drop_table('follower_territory')
    op.drop_index(op.f('ix_follower_history_export_date'), table_name='follower_history')
    op.drop_index(op.f('ix_follower_history_date'), table_name='follower_history')
    op.drop_table('follower_history')
    op.drop_index(op.f('ix_follower_gender_export_date'), table_name='follower_gender')
    op.drop_table('follower_gender')
    op.drop_index(op.f('ix_follower_activity_export_date'), table_name='follower_activity')
    op.drop_index(op.f('ix_follower_activity_date'), table_name='follower_activity')
    op.drop_table('follower_activity')
    op.drop_index(op.f('ix_csv_import_runs_export_date'), table_name='csv_import_runs')
    op.drop_index(op.f('ix_csv_import_runs_created_at'), table_name='csv_import_runs')
    op.drop_table('csv_import_runs')
    # ### end Alembic commands ###
