"""initial schema

Revision ID: f201b6845092
Revises: 
Create Date: 2026-06-15 23:20:20.559539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f201b6845092'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_prompts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('schedule', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_prompts'))
    )
    op.create_table('creators',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('handle', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_creators'))
    )
    op.create_table('market_trends',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('metric', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_trends'))
    )
    op.create_index(op.f('ix_market_trends_captured_at'), 'market_trends', ['captured_at'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('commission_rate', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_table('scrape_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scrape_runs'))
    )
    op.create_index(op.f('ix_scrape_runs_kind'), 'scrape_runs', ['kind'], unique=False)
    op.create_index(op.f('ix_scrape_runs_started_at'), 'scrape_runs', ['started_at'], unique=False)
    op.create_table('ai_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('prompt_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_id'], ['ai_prompts.id'], name=op.f('fk_ai_runs_prompt_id_ai_prompts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_runs'))
    )
    op.create_index(op.f('ix_ai_runs_created_at'), 'ai_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_runs_prompt_id'), 'ai_runs', ['prompt_id'], unique=False)
    op.create_table('sales_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('product_id', sa.String(length=64), nullable=False),
    sa.Column('creator_id', sa.String(length=64), nullable=False),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('gmv', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('commission', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], name=op.f('fk_sales_daily_creator_id_creators')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_sales_daily_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sales_daily')),
    sa.UniqueConstraint('snapshot_date', 'product_id', 'creator_id', name='sales_daily_natural')
    )
    op.create_index(op.f('ix_sales_daily_creator_id'), 'sales_daily', ['creator_id'], unique=False)
    op.create_index(op.f('ix_sales_daily_product_id'), 'sales_daily', ['product_id'], unique=False)
    op.create_index(op.f('ix_sales_daily_snapshot_date'), 'sales_daily', ['snapshot_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_daily_snapshot_date'), table_name='sales_daily')
    op.drop_index(op.f('ix_sales_daily_product_id'), table_name='sales_daily')
    op.drop_index(op.f('ix_sales_daily_creator_id'), table_name='sales_daily')
    op.drop_table('sales_daily')
    op.drop_index(op.f('ix_ai_runs_prompt_id'), table_name='ai_runs')
    op.drop_index(op.f('ix_ai_runs_created_at'), table_name='ai_runs')
    op.drop_table('ai_runs')
    op.drop_index(op.f('ix_scrape_runs_started_at'), table_name='scrape_runs')
    op.drop_index(op.f('ix_scrape_runs_kind'), table_name='scrape_runs')
    op.drop_table('scrape_runs')
    op.drop_table('products')
    op.drop_index(op.f('ix_market_trends_captured_at'), table_name='market_trends')
    op.drop_table('market_trends')
    op.drop_table('creators')
    op.drop_table('ai_prompts')
    # ### end Alembic commands ###
