"""custom_table_meta

Revision ID: f5d134359de9
Revises: efc010eddd8c
Create Date: 2026-06-21 03:39:01.865376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5d134359de9'
down_revision: Union[str, Sequence[str], None] = 'efc010eddd8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_table_meta',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('pg_table_name', sa.String(length=64), nullable=False),
    sa.Column('columns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custom_table_meta')),
    sa.UniqueConstraint('pg_table_name', name=op.f('uq_custom_table_meta_pg_table_name'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_table_meta')
    # ### end Alembic commands ###
