"""Static sticker library for video overlay (Tier 3d).

Sticker PNGs live in backend/data/stickers/*.png (generated by generate_stickers.py).
"""

from __future__ import annotations

import pathlib

from packages.video.storage import data_root

STICKER_CATALOG = {
    "arrow_right": {"label": "Arrow →", "w": 200, "h": 120},
    "arrow_up": {"label": "Arrow ↑", "w": 120, "h": 200},
    "fire": {"label": "Fire 🔥", "w": 120, "h": 160},
    "star": {"label": "Star ⭐", "w": 140, "h": 140},
    "heart": {"label": "Heart ❤", "w": 130, "h": 120},
    "checkmark": {"label": "Check ✓", "w": 120, "h": 120},
    "burst": {"label": "Burst/Sale", "w": 160, "h": 160},
    "label_new": {"label": "NEW!", "w": None, "h": None},
    "label_hot": {"label": "HOT", "w": None, "h": None},
    "label_sale": {"label": "SALE", "w": None, "h": None},
    "label_link": {"label": "LINK IN BIO", "w": None, "h": None},
}


def sticker_path(name: str) -> pathlib.Path:
    """Absolute path to sticker PNG. Raises ValueError if unknown."""
    if name not in STICKER_CATALOG:
        raise ValueError(f"Unknown sticker '{name}'. Available: {list(STICKER_CATALOG)}")
    p = data_root() / "stickers" / f"{name}.png"
    if not p.exists():
        raise FileNotFoundError(f"Sticker PNG not found: {p}. Run: python scripts/generate_stickers.py")
    return p


def default_graphics_for_timeline(cuts: list[dict]) -> list[dict]:
    """Rule-based sticker placement for a talking-head video.

    Returns list of {"name": str, "at": float, "x": int, "y": int, "duration": float}.
    Positions are absolute pixel coords for 1080x1920 canvas.
    """
    if not cuts:
        return []

    graphics: list[dict] = []
    t = 0.0

    for i, cut in enumerate(cuts):
        dur = float(cut.get("durationSec", cut.get("duration", 3.0)))
        label = cut.get("label", "")

        if i == 0 and label in ("opening", "hook"):
            # Fire sticker top-right at 0.5s
            graphics.append({"name": "fire", "at": t + 0.5, "x": 900, "y": 120, "duration": 2.0})

        if label == "product_mention":
            graphics.append({"name": "arrow_up", "at": t + 0.3, "x": 480, "y": 1500, "duration": 2.5})
            graphics.append({"name": "label_link", "at": t + 0.5, "x": 300, "y": 1720, "duration": 2.0})

        if label == "conclusion" and i == len(cuts) - 1:
            graphics.append({"name": "label_new", "at": t + 0.2, "x": 60, "y": 1700, "duration": dur - 0.4})

        t += dur

    return graphics
