import { Fragment, type ReactNode } from "react";
import GLOSSARY from "./thai-glossary.json";
import { glueRepeat, keepSegments } from "./ThaiText";

/**
 * Line breaking for long Thai copy rendered on the server: keepThai's words,
 * plus two things only the server can afford.
 *
 * 1. The glossary (thai-glossary.json, generated by scripts/thai-glossary.mjs
 *    from the site's own copy): every word a larger Thai dictionary finds that
 *    Chrome's dictionary (ICU) cuts in the middle — "ความช่วย|เหลือ",
 *    "ทุ|กช็อต", "ติด|ตั้ง". A glossary word is kept whole only where it
 *    starts on a word boundary ICU agrees with, so a short entry can never be
 *    matched across two other words ("ด้วย|การ" does not contain "ยก").
 * 2. Short words that lean on the next one — a line must not end right after
 *    them: "ไม่ / กิน" reads as "no" at the end of the line; "การ / ขาดรายได้",
 *    "ความ / รับผิด", "ผู้ / ปกครอง", "ค่า / บริการ", "ใน / ห้องตัดต่อ" split a
 *    phrase the reader takes as one word. Each is glued to the word after it.
 *
 * Server components only: a client component would segment again in the
 * browser, whose dictionary may differ, and the hydrated text would not match
 * (client components use keepThai). The text is unchanged apart from the
 * no-break space before ๆ; the wrappers are plain spans.
 */

const LEANS_ON_NEXT = new Set(["ไม่", "การ", "ความ", "ผู้", "ค่า", "ใน"]);

/** Glossary words by first character, longest first. */
const BY_FIRST = new Map<string, string[]>();
for (const word of GLOSSARY) {
  const list = BY_FIRST.get(word[0]) ?? [];
  list.push(word);
  BY_FIRST.set(word[0], list);
}
for (const list of BY_FIRST.values()) list.sort((a, b) => b.length - a.length);

let words: Intl.Segmenter | undefined;

type Token = { text: string; keep: boolean; word: boolean };

/** One run of unprotected text as tokens: ICU's words, with glossary words kept whole. */
function tokenize(text: string, tokens: Token[]) {
  words ??= new Intl.Segmenter("th", { granularity: "word" });
  const pieces = [...words.segment(text)];
  let i = 0;
  while (i < pieces.length) {
    const piece = pieces[i];
    const found = BY_FIRST.get(piece.segment[0])?.find((word) => text.startsWith(word, piece.index));
    if (!found) {
      tokens.push({ text: piece.segment, keep: false, word: !!piece.isWordLike });
      i += 1;
      continue;
    }
    tokens.push({ text: found, keep: true, word: true });
    const end = piece.index + found.length;
    while (i < pieces.length && pieces[i].index + pieces[i].segment.length <= end) i += 1;
    // The glossary word ended inside ICU's next "word": the rest of it stands alone.
    if (i < pieces.length && pieces[i].index < end) {
      tokens.push({ text: text.slice(end, pieces[i].index + pieces[i].segment.length), keep: false, word: true });
      i += 1;
    }
  }
}

export function keepThaiProse(source: string): ReactNode {
  const text = glueRepeat(source);
  const tokens: Token[] = [];
  for (const part of keepSegments(text)) {
    if (part.keep) tokens.push({ text: part.text, keep: true, word: true });
    else tokenize(part.text, tokens);
  }
  const runs: { text: string; keep: boolean }[] = [];
  for (let index = 0; index < tokens.length; index++) {
    const token = tokens[index];
    if (!token.keep && LEANS_ON_NEXT.has(token.text) && tokens[index + 1]?.word) {
      let glued = token.text;
      let next = index + 1;
      glued += tokens[next].text;
      while (!tokens[next].keep && LEANS_ON_NEXT.has(tokens[next].text) && tokens[next + 1]?.word) glued += tokens[++next].text;
      runs.push({ text: glued, keep: true });
      index = next;
    } else if (!token.keep && runs.length > 0 && !runs[runs.length - 1].keep) {
      runs[runs.length - 1].text += token.text;
    } else {
      runs.push({ text: token.text, keep: token.keep });
    }
  }
  if (runs.length === 1 && !runs[0].keep) return text;
  return runs.map((run, index) =>
    run.keep ? (
      <span key={index} className="kt">
        {run.text}
      </span>
    ) : (
      <Fragment key={index}>{run.text}</Fragment>
    ),
  );
}
